doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Users:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Users/Infrastructure/Database/ORM'
                prefix: 'App\Users\Domain\Entity'
                alias: Users
            TradingBot:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/TradingBot/Infrastructure/Database/ORM'
                prefix: 'App\TradingBot\Domain\Entity'
                alias: TradingBot
            Exchange:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Exchange/Infrastructure/Database/ORM'
                prefix: 'App\Exchange\Domain\Entity'
                alias: Exchange
            CryptoCurrency:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/CryptoCurrency/Infrastructure/Database/ORM'
                prefix: 'App\CryptoCurrency\Domain\Entity'
                alias: CryptoCurrency
            Transaction:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Transaction/Infrastructure/Database/ORM'
                prefix: 'App\Transaction\Domain\Entity'
                alias: Transaction
            Portfolio:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Portfolio/Infrastructure/Database/ORM'
                prefix: 'App\Portfolio\Domain\Entity'
                alias: Portfolio

#when@test:
#    doctrine:
#        dbal:
#            # "TEST_TOKEN" is typically set by ParaTest
#            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
