transaction_list:
  path: /transaction/list
  methods: [GET, POST]
  controller : App\Shared\Infrastructure\Controller\Transaction\GetAllController

transaction_delete:
  path: /transaction/{id}/delete
  methods: [GET]
  controller: App\Shared\Infrastructure\Controller\Transaction\DeleteController
